"""Public API for the JOREK weak-equation symbolic DSL."""

from .channels import ToroidalChannels, split_toroidal_channels
from .equations import ConstraintEquation, EvolutionEquation, LinearizedEquation
from .exceptions import (
    EquationDslError,
    InvalidDeclarationError,
    MissingDerivativeError,
    UnsupportedExpressionError,
)
from .external import ExternalFunction, LinearizationPolicy, external_function
from .fortran import FortranPrinter, fortran
from .linearization import jacobian_blocks, resolve_current, variation
from .operators import (
    R,
    Z,
    phi,
    SpatialDerivative,
    PoloidalBracket,
    bracket,
    dR,
    dZ,
    derivative,
    dot,
    dphi,
    element_bracket,
    ds,
    dt,
    expand_brackets,
    expand_derivatives,
    grad,
    lower_brackets_to_element,
)
from .symbols import (
    Field,
    FieldRole,
    FieldValue,
    Frozen,
    TestFunction,
    coefficient,
    delta,
    field,
    freeze,
    frozen_abs,
    previous_delta,
    test_function,
    trial,
)
from .fortran_source import FortranComparisonError

__all__ = [
    "ConstraintEquation",
    "EquationDslError",
    "EvolutionEquation",
    "ExternalFunction",
    "FortranPrinter",
    "FortranComparisonError",
    "Field",
    "FieldRole",
    "FieldValue",
    "Frozen",
    "InvalidDeclarationError",
    "LinearizationPolicy",
    "LinearizedEquation",
    "MissingDerivativeError",
    "R",
    "SpatialDerivative",
    "PoloidalBracket",
    "TestFunction",
    "ToroidalChannels",
    "UnsupportedExpressionError",
    "Z",
    "bracket",
    "coefficient",
    "dR",
    "dZ",
    "delta",
    "derivative",
    "dot",
    "dphi",
    "element_bracket",
    "ds",
    "dt",
    "external_function",
    "expand_brackets",
    "expand_derivatives",
    "field",
    "freeze",
    "frozen_abs",
    "fortran",
    "grad",
    "jacobian_blocks",
    "lower_brackets_to_element",
    "phi",
    "previous_delta",
    "resolve_current",
    "test_function",
    "split_toroidal_channels",
    "trial",
    "variation",
]
