"""LaTeX notation for the model-600 documentation.

Rendering data only: the equations themselves are in ``model600.py``.  This
module says how each name used there is written in
``docs/physics/base_fluid_models/RMHD/weak_form.md``; names that are not
listed are rendered from their spelling (``D_par_local -> D_{par,local}``).
"""

# The evolved fields, in the order of the variables table.
FIELDS = {
    'psi': '\\psi',
    'u': 'u',
    'j': 'j',
    'omega': '\\omega',
    'rho': '\\rho',
    'rhoimp': '\\rho_{imp}',
    'rhon': '\\rho_n',
    'vpar': 'v_\\parallel',
    'T': 'T',
    'Ti': 'T_i',
    'Te': 'T_e',
}

# Work values, coefficients and local names of the equations.
SYMBOLS = {
    'T_or_Te': '\\check{T}_e',
    'Te_gen': '\\hat{T}_e',
    'ion_temperature': '\\tilde{T}_i',
    'R': 'R',
    'xjac': '\\mathcal{J}',
    'dV': 'w_V',
    'F0': 'F_0',
    'tauIC': '\\tau_{IC}',
    'tstep': '\\Delta t',
    'GAMMA': '\\Gamma',
    'gamma': '\\Gamma',
    'ne': 'n_e',
    'rho_main': '\\rho_{main}',
    'rho_corr': '\\rho^{\\mathrm{c}}',
    'rho_hat': '\\hat{\\rho}',
    'bb2': 'B^2',
    'Pe': 'p_e',
    'pressure': 'p',
    'pi': 'p_i',
    'W_dia': 'W_{dia}',
    'ion_density': 'n_i',
    'ion_pressure': 'p_i',
    'electron_pressure': 'p_e',
    'electron_density': 'n_e^{\\mathrm{c}}',
    'ionization_energy': 'W_{ion}',
    'visco_par_eff': '\\mu_\\parallel^{\\mathrm{eff}}',
    'source_dens_tot': 'S_n',
    'D_par_tot': 'D_\\parallel^{\\mathrm{tot}}',
    'D_par_imp_tot': 'D_{\\parallel,imp}^{\\mathrm{tot}}',
    'd_par_tot': '\\hat{D}_\\parallel',
    'd_par_imp_tot': '\\hat{D}_{\\parallel,imp}',
    'alpha_e_value': '\\alpha_e',
    'sion_rate': 'S_{ion}',
    'srec_rate': 'S_{rec}',
    'grad_v': '\\nabla_{\\mathrm{pol}} v',
    'grad_u': '\\nabla_{\\mathrm{pol}} u',
    'grad_omega': '\\nabla_{\\mathrm{pol}} \\omega',
    'grad_vpar': '\\nabla_{\\mathrm{pol}} v_\\parallel',
    'lap_v': '\\nabla^2_{\\mathrm{pol}} v',
    'lap_omega': '\\nabla^2_{\\mathrm{pol}} \\omega',
    'neutral_sources': 'S_{neut}',
    'current_source': 'j_{src}',
    'Jb': 'j_b',
    'visco_par': '\\mu_\\parallel',
    'visco_par_num': '\\mu_{\\parallel,num}',
    'visco_par_par': '\\mu_{\\parallel\\parallel}',
    'visco_par_sc_num': '\\mu_{\\parallel,sc}',
    'D_prof': 'D_\\perp',
    'D_prof_imp': 'D_{\\perp,imp}',
    'D_par_local': 'D_\\parallel',
    'D_par_local_imp': 'D_{\\parallel,imp}',
    'D_par_sc_num': 'D_{\\parallel,sc}',
    'D_par_imp_sc_num': 'D_{\\parallel,imp,sc}',
    'tau_sc': '\\tau_{sc}',
    'V_prof_pinch': 'V_{pinch}',
    'fact_conservative_u': 'f_{cons}',
    'delta_n_convection': '\\delta_{n}',
    'dV_dpsi_source': '\\frac{\\mathrm{d}V_{rot}}{\\mathrm{d}\\psi}',
    'particle_source': 'S_p',
    'source_pellet': 'S_{pellet}',
    'source_bg_drift': 'S_{bg,drift}',
    'source_imp_drift': 'S_{imp,drift}',
    'aux_rho0': 'S_\\rho^{aux}',
    'aux_mom_par0': 'M_\\parallel^{aux}',
    'heat_source_total': 'H',
    'heat_source_i': 'H_i',
    'heat_source_e': 'H_e',
    'aux_E0': 'H^{aux}',
    'aux_E0_Ti': 'H_i^{aux}',
    'aux_E0_Te': 'H_e^{aux}',
    'power_dens_teleport_ju': 'P_{teleport}',
    'ksi_ion_norm': '\\xi_{ion}',
    'implicit_heat_source': 'c_{floor}',
    'T_min_neg': 'T_{min}',
    'Tie_min_neg': 'T_{min}',
    'aux_jre': 'j_{RE}',
    'aux_jre_ind': 'j_{RE}^{ind}',
    'aux_P_par_re': 'P_\\parallel^{RE}',
    'aux_P_perp_re': 'P_\\perp^{RE}',
    'aux_divPIR_perp': '\\Pi_R^{RE}',
    'aux_divPIZ_perp': '\\Pi_Z^{RE}',
    'visco_fact_old': 'f_\\mu^{old}',
    'visco_fact_new': 'f_\\mu^{new}',
    'visco_par_heating': '\\mu_{\\parallel,heat}',
    'D_perp_num_psin': 'D_{\\perp,num}',
    'Dn0x': 'D_{n,R}',
    'Dn0y': 'D_{n,Z}',
    'Dn0p': 'D_{n,\\phi}',
    'source_neutral_drift': 'S_n^{drift}',
    'Dn_perp_num': 'D_{\\perp,num}^{n}',
    'ZK_perp_num_psin': '\\kappa_{\\perp,num}',
    'ZK_i_perp_num_psin': '\\kappa_{\\perp,num}^{i}',
    'ZK_e_perp_num_psin': '\\kappa_{\\perp,num}^{e}',
    'tgnum_u': 'c_{TG}^{u}',
    'tgnum_rho': 'c_{TG}^{\\rho}',
    'tgnum_vpar': 'c_{TG}^{v_\\parallel}',
    'tgnum_rhoimp': 'c_{TG}^{\\rho_{imp}}',
    'tgnum_T': 'c_{TG}^{T}',
    'tgnum_Ti': 'c_{TG}^{T_i}',
    'tgnum_Te': 'c_{TG}^{T_e}',
    'psi_gradient': '\\nabla_{\\mathrm{pol}} \\psi',
    'rotation_shear': '\\nabla_{\\mathrm{pol}}(v_\\parallel - V_{rot})',
}

# State-dependent functions.  ``{0}`` makes the symbol a template for the
# argument; otherwise the arguments follow in parentheses.
FUNCTIONS = {
    'eta': '\\eta',
    'eta_num_T': '\\eta_{num}',
    'visco': '\\mu_\\perp',
    'visco_num': '\\mu_{num}',
    'alpha_i_state': '\\alpha_i',
    'dvisco_state': "\\mu_\\perp'",
    'Sion_rate': 'S_{ion}',
    'Srec_rate': 'S_{rec}',
    'alpha_e_state': '\\alpha_e',
    'alpha_e_bis_state': "\\alpha_e'",
    'alpha_e_temperature': 'A_e',
    'alpha_imp_bis_state': "\\alpha_{imp}'",
    'alpha_imp_temperature': 'A_{imp}',
    'corr_neg_dens': '{0}^{\\mathrm{c}}',
    'corr_neg_dens_imp': '{0}^{\\mathrm{c}}',
    'corr_neg_dens_n': '{0}^{\\mathrm{c}}',
    'W_dia_single': 'W_{dia}',
    'W_dia_two': 'W_{dia}',
    'ZKi_par': '\\kappa_{\\parallel,i}',
    'ZKi_perp': '\\kappa_{\\perp,i}',
    'visco_heating': '\\mu_{heat}',
    'Ti_e_exchange': 'Q_{ie}',
    'Ti_floor': 'T_i^{floor}',
    'Ti_floor_exp': '\\epsilon_i^{floor}',
    'E_ion_bg_state': 'E_{ion}^{bg}',
    'E_ion_state': 'E_{ion}',
    'ZKe_par': '\\kappa_{\\parallel,e}',
    'ZKe_perp': '\\kappa_{\\perp,e}',
    'eta_ohm_e': '\\eta_{ohm}',
    'LradDrays': 'L_{rays}',
    'LradDcont': 'L_{cont}',
    'frad_bg_state': 'f_{rad}^{bg}',
    'Lrad_state': 'L_{rad}',
    'Te_i_exchange': 'Q_{ei}',
    'Te_floor': 'T_e^{floor}',
    'Te_floor_exp': '\\epsilon_e^{floor}',
    'ZK_par': '\\kappa_\\parallel',
    'ZK_perp': '\\kappa_\\perp',
    'T_floor': 'T^{floor}',
    'T_floor_exp': '\\epsilon^{floor}',
}

# Shared operators (the ``_helper`` functions of model600.py), grouped as on
# the page.  ``template`` is how a call is written, with ``{param}``
# placeholders (``{param!}`` inserts the argument without parentheses);
# ``display`` names a parameter in the operator's own definition.
HELPERS = {
    '_B2': dict(
        group='Magnetic field',
        title='Magnetic field strength',
        description='The square of the total field, with $\\mathbf{B} = F_0\\,\\nabla\\phi + \\nabla\\psi\\times\\nabla\\phi$.',
        template='B^2({flux!})',
        display={'flux': '\\psi'},
    ),
    '_B2_pol': dict(
        group='Magnetic field',
        title='Poloidal magnetic field strength',
        description='The square of the poloidal field, $\\lvert\\nabla_{\\mathrm{pol}}\\psi\\times\\nabla\\phi\\rvert^2$. Since $F_0$ is constant, $\\partial_t B^2 = \\partial_t B^2_{pol}$.',
        template='B^2_{pol}({flux!})',
        display={'flux': '\\psi'},
    ),
    '_B_dot_grad': dict(
        group='Magnetic field',
        title='Parallel gradient',
        description='The derivative along the field. With `st_form` the bracket is written in element coordinates, $[f,\\psi]^{st}$, which is the same quantity.',
        template='\\mathbf{B}\\cdot\\nabla {value}',
        display={'value': 'f'},
    ),
    '_rho_hat': dict(
        group='Magnetic field',
        title='Weighted density',
        description='The density weighted by $R^2$, as it enters the momentum equation.',
        template='\\hat{\\rho}',
        display={'value': '\\rho'},
    ),
    '_u_convection': dict(
        group='Convection',
        title='Convection by the ExB flow',
        description='Advection and compression of a density by the $E\\times B$ flow of stream function $u$.',
        template='\\mathcal{C}_u({density!})',
        display={'density': 'n'},
    ),
    '_parallel_convection': dict(
        group='Convection',
        title='Parallel convection',
        description='Advection and compression of a density by the parallel flow $v_\\parallel$.',
        template='\\mathcal{C}_\\parallel({quantity!})',
        display={'quantity': 'n'},
    ),
    '_press_u_convection': dict(
        group='Convection',
        title='Pressure convection by the ExB flow',
        description='The same for a pressure: the compression carries the factor $\\Gamma$.',
        template='\\mathcal{C}_u^{p}({pressure!})',
        display={'pressure': 'p', 'bracket': '[\\cdot,\\cdot]'},
    ),
    '_press_parallel_convection': dict(
        group='Convection',
        title='Parallel pressure convection',
        description='The same for a pressure along the field.',
        template='\\mathcal{C}_\\parallel^{p}({pressure!})',
        display={'pressure': 'p'},
    ),
    '_par_diff_intg_by_parts': dict(
        group='Diffusion',
        title='Parallel diffusion',
        description='Diffusion along the magnetic field, after integration by parts.',
        template='\\mathcal{D}_\\parallel({v!}, {density!})',
        display={'density': 'n'},
    ),
    '_diffusion_tot_intg_by_parts': dict(
        group='Diffusion',
        title='Total diffusion',
        description='Isotropic diffusion, including the toroidal derivative, after integration by parts.',
        template='\\mathcal{D}_{tot}({test!}, {value!})',
        display={'test': 'v', 'value': 'f'},
    ),
    '_dens_tgnum_intg_by_parts': dict(
        group='Numerical stabilization',
        title='Taylor-Galerkin stabilization of a density',
        description='Taylor-Galerkin stabilization of the convection by the $E\\times B$ and parallel flows.',
        template='\\mathcal{T}_n({v!}, {density!})',
        display={'density': 'n'},
    ),
    '_energy_tgnum': dict(
        group='Numerical stabilization',
        title='Taylor-Galerkin stabilization of an energy equation',
        description='The same for a pressure, with the coefficient $c$ of the equation.',
        template='\\mathcal{T}_p({v!}, {pressure!}; {factor!})',
        display={'pressure': 'p', 'factor': 'c'},
    ),
    '_heating_floor': dict(
        group='Numerical stabilization',
        title='Heating at the temperature floor',
        description='Implicit heat source that keeps a temperature away from its floor $T_{min}$. $\\epsilon$ and $T^{floor}$ are the floor functions of the element routine (`Ti_floor_exp`, `Ti0_floor` and their electron and single-temperature counterparts).',
        template='\\mathcal{H}({v!}, {exponential!}, {floor!}, {minimum!})',
        display={'exponential': '\\epsilon', 'floor': 'T^{floor}', 'minimum': 'T_{min}'},
    ),
    '_diamagnetic_pressure': dict(
        group='Diamagnetic terms',
        title='Diamagnetic ion pressure',
        description='The ion pressure of the diamagnetic terms, as built in `construct_pressure`. The single-temperature model evolves the total temperature, so the ion temperature is $T/2$ there. $\\alpha_i$ does not depend on the temperature.',
        template='p_i^{dia}',
        display={},
    ),
    '_diamagnetic_viscosity': dict(
        group='Diamagnetic terms',
        title='Diamagnetic viscosity',
        description="The element routine's `W_dia`. It is built from the ion pressure alone, so it has no explicit electron-temperature dependence.",
        template='W_{dia}',
        display={},
    ),
    '_released_kinetic_energy': dict(
        group='Sources and heating',
        title='Particle sources releasing kinetic energy',
        description='Particle sources whose kinetic energy is released into the ions: ionization of neutrals and the external sources.',
        template='S_{kin}({T_or_Te!})',
        display={'T_or_Te': 'T'},
    ),
    '_parallel_viscous_heating': dict(
        group='Sources and heating',
        title='Parallel viscous heating',
        description='Heating by the parallel viscosity.',
        template='Q_{\\mu\\parallel}({v!})',
        display={},
    ),
    '_u_viscous_heating': dict(
        group='Sources and heating',
        title='Perpendicular viscous heating',
        description='Heating by the perpendicular viscosity of the $u$ flow, with the heating viscosity $\\mu_{heat}$.',
        template='Q_{\\mu\\perp}({v!}, {heating!})',
        display={'heating': '\\mu_{heat}'},
    ),
    '_kinetic_coupling': dict(
        group='Sources and heating',
        title='Coupling to the kinetic neutral and impurity model',
        description='Energy and momentum handed over by the kinetic neutral and impurity model.',
        template='Q_{kin}({v!})',
        display={},
    ),
    '_ionization_energy_transport': dict(
        group='Sources and heating',
        title='Transport of the ionization potential energy',
        description='The ionization potential energy $W$ is convected like a density, and diffuses with the impurity and main-ion densities that carry it.',
        template='\\mathcal{Q}_{ion}({v!}, {energy!}, {temperature!})',
        display={'energy': 'W', 'temperature': 'T'},
    ),
}

# The equations, in the order of the page: function in model600.py, title,
# anchor suffix, and an optional paragraph shown above the equation's terms.
EQUATIONS = (
    ("induction_equation_1", "Induction equation (`var_psi`)", "psi", ""),
    ("momentum_equation_2", "Perpendicular momentum equation (`var_u`)", "u", ""),
    ("current_constraint_equation_zj", "Current definition (`var_zj`)", "zj", ""),
    ("vorticity_constraint_equation_w", "Vorticity definition (`var_w`)", "w", ""),
    ("density_equation_rho", "Density equation (`var_rho`)", "rho", ""),
    ("parallel_velocity_equation_vpar", "Parallel velocity equation (`var_vpar`)", "vpar",
     r"The equation is the projection of the momentum equation on $\mathbf{B}$. "
     r"With the parallel flow $v_\parallel\mathbf{B}$ and "
     r"$\mathbf{B}\cdot\partial_t\mathbf{B} = \frac{1}{2}\partial_t B^2 = \frac{1}{2}\partial_t B^2_{pol}$, "
     r"$\mathbf{B}\cdot\rho\,\partial_t(v_\parallel\mathbf{B}) = \rho\,\big(B^2\,\partial_t v_\parallel "
     r"+ \frac{1}{2}v_\parallel\,\partial_t B^2_{pol}\big)$: the time derivative acts separately on "
     r"$v_\parallel$ and on $B^2_{pol}$, and is not the derivative of $\rho\,v_\parallel B^2$. "
     r"In the conservative form ($f_{cons} = 1$) it adds $v_\parallel B^2\,\partial_t\rho$. "
     r"The element routine uses the corrected density $\rho^{\mathrm{c}}$ in the first two terms."),
    ("impurity_density_equation_rhoimp", "Impurity density equation (`var_rhoimp`)", "rhoimp",
     r"`with_TiTe` has no effect here; it is accepted so that every density equation has the "
     r"same interface."),
    ("neutral_density_equation_rhon", "Neutral density equation (`var_rhon`)", "rhon",
     r"Fluid neutrals are diffused with an anisotropic diffusivity, convected with the plasma flow "
     r"when $\delta_n = 1$, ionized and recombined with the same rates as in the density "
     r"equation, and fed by a prescribed source."),
    ("ion_energy_equation_Ti", "Ion energy equation (`var_Ti`)", "Ti", ""),
    ("electron_energy_equation_Te", "Electron energy equation (`var_Te`)", "Te", ""),
    ("total_energy_equation_T", "Single-temperature energy equation (`var_T`)", "T", ""),
)

